name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
      API_URL: https://api-sandbox.lolcatz.tv
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.DOCKER_REGISTRY }}
          username: x-access-token
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: VERSION="${GITHUB_SHA:0:8}-sandbox" make build publish
        if: github.ref == 'refs/heads/build-test'
