name: Build and test

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - name: npm build
        run: |
          npm install --silent
          npm install react-scripts@3.3.0
          npm run build
